### ISSUE TITLE
NetworkSDK download multi file from multi url

### ISSUE THREAD

**Issue by wilddylan** [WildDylan/NetworkSDK#1]
Now, NetworkSDK download request only can download single file, Next version will add download multi file and upload multi files.

This is an milestone

**Comment by wilddylan** [comment]
Multi download request can be send by `NetworkMultiRequest`

d8eb00d

**Comment by JC-Hu** [comment]
自己玩的挺嗨啊 -。-

**Comment by wilddylan** [comment]
自己写库嘛，写个里程碑约束一下自己。
一些想法什么的，怕以后忘记了，就先提个issue给自己看，这也是跟别人学的。 感觉挺好的。
